module.exports.propertyService = require('./property.service')
module.exports.userService = require('./user.service')
module.exports.tokenService = require('./token.service')
module.exports.locationService = require('./location.service')
module.exports.sellerService = require('./seller.service')
module.exports.imageService = require('./image.service')
