module.exports.propertyController = require('./property.controller')
module.exports.userController = require('./user.controller')
module.exports.locationController = require('./location.controller')
module.exports.sellerController = require('./seller.controller')
module.exports.contactController = require('./contact.controller')
